In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [3]:
df = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/Dataset/Car_details.csv")
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
1,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
2,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
3,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0
4,Hyundai Xcent 1.2 VTVT E Plus,2017,440000,45000,Petrol,Individual,Manual,First Owner,20.14 kmpl,1197 CC,81.86 bhp,113.75nm@ 4000rpm,5.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8127 entries, 0 to 8126
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8127 non-null   object
 1   year           8127 non-null   int64
 2   selling_price  8127 non-null   int64
 3   km_driven      8127 non-null   int64
 4   fuel           8127 non-null   object
 5   seller_type    8127 non-null   object
 6   transmission   8127 non-null   object
 7   owner          8127 non-null   object
 8   mileage        7906 non-null   object
 9   engine         7906 non-null   object
 10  max_power      7912 non-null   object
 11  torque         7905 non-null   object
 12  seats          7906 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.5+ KB